import '../entities/user_entity.dart';

abstract class IUserRepository {
  /// Fetches a user by their unique [id]
  Future<UserEntity?> getUserById(String id);

  /// Fetches all users available
  Future<List<UserEntity>> getAllUsers();

  /// Create or add a new user. Returns the newly created user (with potentially new id generated by backend).
  Future<UserEntity> createUser(UserEntity user);

  /// Updates an existing user entirely or partially.
  Future<UserEntity> updateUser(UserEntity user);

  /// Deletes a user by [id]
  Future<bool> deleteUser(String id);
}
